### PR TITLE
Use graphql-java 4.2; Move away from deprecated API use

### PR DESCRIPTION
**Pull request by timtebeek**

### CODE REVIEW

**Comment by tazmaniax** [comment]
Hi @jcrygier , there seems to be a bunch of changes at https://github.com/cchiaverini/graphql-jpa and I wonder if it makes sense to merge those changes to here so everyone benefits of combined effort. Maybe suggest a pull request?

**Comment by cchiaverini** [comment]
The changes in my branch are somewhat fluid right now based upon the needs of my prototype project.  While I'm thrilled that people are interested in them, I haven't submitted a pull request back to the main repository because I don't consider them ready for public consumption.  There are still outstanding issues regarding the N+1 problem, nested filtering, etc. that should be addressed.  I've also been working in a silo, so my changes/needs may conflict with @jcrygier 's vision.

**Comment by tazmaniax** [comment]
@cchiaverini completely understand and makes sense your approach. Just want to spread awareness and make connections so we can collectively move this project forward. Thanks to @jcrygier for starting it and yourself for spending time evolving it.

**Comment by tazmaniax** [comment]
@cchiaverini I've also got some changes that I'm not sure about creating a pull request for and it would be good to discuss somewhere. Maybe a Github issue is a good place to start

**Pull request merged**
