### PR TITLE
graphql-java v2.1.0

### PR DESCRIPTION
**Pull request by timtebeek**

### CODE REVIEW

**Comment by timtebeek** [comment]
@jcrygier As seen here the travis build has some issues with the bintray user; Would it be possible for you to move that to a separate profile/task? https://travis-ci.org/timtebeek/graphql-jpa

And would you be willing to merge these changes and push a release out that I can use in my projects? I'd like to start using this if possible..

**Comment by jcrygier** [comment]
@timtebeek Thanks for the pull...I'm no BinTray / Travis Expert, but I'll definitely work on getting them integrated, so that builds are trivial to push out.

I'm traveling for work this week, so it may take me a few days to get this merged in and deploys to BinTray automatically.

**Comment by jcrygier** [comment]
@timtebeek I had some extra time....so I think I have everything squared away.  Please check out the v0.2, that's recently been deployed from Travis, and let me know of any issues.

Thanks!

**Comment by timtebeek** [comment]
Great thanks! Couldn't find where it's been deployed to, but the current master branch works fine when checked out locally. :)

Having a minor issue now with mapping Enums, details posted in issue #5.

**Pull request merged**
