### PR TITLE
Handle Short and Date

### PR DESCRIPTION
**Pull request by timtebeek**
Need this for a project of mine; Not sure if `GraphQLScalarType GraphQLDate` is exactly right as is, especially the exception handling. Could you have a look @jcrygier ?

Also it seems I could simply replace `JavaScalar.GraphQLLong` with `Scalar.GraphQLLong` from `graphql-java`, so I did. Hope that's OK. :)

### CODE REVIEW

**Comment by timtebeek** [comment]
@jcrygier I've updated the code slightly to return null as per the specification; Could you have a look at merging this?

And on a broader note: are you actively maintaining this project, or could this be something for inclusion into either https://github.com/graphql-java or https://github.com/oembedler/spring-graphql-common? The latter seems to have pretty neat protection against malicious queries, so it could be nice to see a merger of the two functionalities.

**Comment by jcrygier** [comment]
@timtebeek I can't say I "actively" maintain this project...as we're not using it in my current job.  So that just leaves nights and weekends to work on it, which I honestly don't have a lot of time to do so lately.

I'm more than happy to review and accept pull requests, or also more than happy to include this project in a larger body of work such as graphql-java or spring-graphql-common, if they're willing to have it.

Also, if you'd like me to add you as a collaborator to this project, just let me know...I'd be glad to (as you've been contributing some good work lately)!

**Comment by timtebeek** [comment]
Thanks for the merge! And thanks for the honest comments about the future of the project.. :) I'm all too familiar with only having nights and weekends available for hobby projects of my own, so I understand where you're coming from. For now I'll keep sending pull requests your way for the smaller items that pop-up.. I'm not too familiar with the code base yet to bypass a critical second look I guess.

Good to have your blessing on maybe getting this included into a larger body of work; I'll reach out and see what kind of responses we get. In my opinion it could be a worthwhile addition to the other projects out there already, so let's see how that goes.

**Comment by jean-morissette** [comment]
Please, do not merge this project under Spring umbrella. Now everyone is using Spring.

**Pull request merged**
